name: main
on:
  push:
    branches: [main]
    tags: v*
  pull_request:
    branches: [main]
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.17.x
          - 1.18.x
          - 1.19.x
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -v ./...
